openapi: 3.0.0
info:
  version: 1.0.0
  title: OpenAPI 3.0 and Mock Server Example
  description: >
    This specification has 3 purposes:

    - Act as an example OpenAPI 3.0 specification

    - Use ReDoc to display the specification in a clear manner

    - Demonstrate how to create mock server from OpenAPI 3.0 specification
    quickly
servers:
  - url: 'http://localhost:8000'
    description: Mock Server
